spring.application.name=demo-spring-security
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.url=jdbc:postgresql://6SW0msrAcVskWMy2m3qsUPQiTVYFPdSD@dpg-d70hvs75gffc73dtc8ag-a.frankfurt-postgres.render.com/spring_p25s
spring.datasource.username=springuser
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=6SW0msrAcVskWMy2m3qsUPQiTVYFPdSD
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

