name: Maven Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut koden
        uses: actions/checkout@v4

      - name: Installera Java och konfigurera Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Bygg projektet
        run: mvn -B clean package
        env:
          GITHUB_TOKEN: ${{ secrets.PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hakangleissman
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: hakangleissman/demo-spring-security:1.0.0